version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb/
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    env_file: .env
    restart: on-failure # "on-failure", container will be restarted
    expose:
      - "3306"

networks:
    inception:
      driver: bridge

# volumes used by multiple containers
volumes:
    mariadb-data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: /home/nakawashi/data/mariadb-data
        #device: /mnt/c/Users/Nakawashi/Documents/test