version: '3'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb/
    volumes:
      - mariadb-data:/var/lib/mysql:rw
    env_file: .env
    restart: on-failure # "on-failure", container will be restarted
    expose:
      - "3306"
  nginx:
    container_name: nginx
    volumes:
      - wordpress-data:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress-data:/var/www/wordpress/
    networks:
      - inception
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

networks:
    inception:
      driver: bridge

# volumes used by multiple containers
volumes:
    mariadb-data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: /home/nakawashi/data/mariadb-data
    wordpress-data:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: /home/nakawashi/data/wordpress-data