version: '3'

services:

  # database
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb/
    image: mariadb:1.1
    volumes:
      - volume_mariadb:/var/lib/mysql:rw
    env_file: .env
    restart: on-failure
    expose:
      - "3306"

  # web server
  nginx:
    container_name: nginx
    volumes:
      - volume_wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx:1.1
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  # wordrpress website
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - volume_wordpress:/var/www/wordpress/
    networks:
      - inception
    build: ./requirements/wordpress/
    image: wordpress:1.1
    depends_on:
      - mariadb
    restart: on-failure
    expose:
      - "9000"

# network
networks:
  inception:
    driver: bridge

# volumes used by multiple containers
volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/${LOGIN}/data/mariadb/
  volume_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/${LOGIN}/data/wordpress/